# Generated by Django 4.0.7 on 2022-08-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='countries',
            new_name='country',
        ),
    ]
